---
title: "completed page codebooks work"
author: "David Reinstein, Toby Jolly, Gerhard Riener"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r codebooks, eval=FALSE}

#eval=params$runcodebooks

#print(dfSummary(UCFdd),file="completish_fundraisers.html")

cb_UCFdd <- codebook(UCFdd, survey_repetition = "single", metadata_table = FALSE) #Gerhard: this could also create an html; or make this as a separate markdown. It takes a long time to run... so maybe don't do it here

cb_UCFdd_fd <- codebook(UCFdd_fd, survey_repetition = "single", metadata_table = FALSE) #Gerhard: this could also create an html; or make this as a separate markdown. It takes a long time to run... so maybe don't do it here

#todo: generate variable for 'cumulative sum raised' and 'cum percent raised'. Next create variable for 'time elapsed until 95\% of donations raised'. Finally, collapse this by fundraiser, and give statistics on the output.

#TODO: 
```
