---
title: "Codebook: JustGiving Fundraiser pages; donation variables aggregated; UK only, pages with positive amounts raised;  plausibly-completed pages"
author: "David Reinstein, Toby Jolly, Gerhard Riener"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

## Setup and import data 

```{r setup-and-import-data, include=FALSE, message=FALSE, cache=TRUE}

knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
library(knitr)
library(haven)
library(tidyverse)
library(codebook)
library(here)


source(here("R","baseopt_jg.R")) #basic options, definitions, abbreviations for functions

data_folder <- here('input_data')

donations_folder <- file.path(data_folder, 'donations')
fundraising_folder <- file.path(data_folder, 'fundraisers')

#source(here("R","combine_available_data.R")) #check - many parsing failures

source(here("R","scopingfunctions.R")) #tabylstuff, dotplot_func, boxplot_func, geom_mean, sidebyside, huxoptions


```
## Change to lower_snake_case
```{r, include=FALSE}
uc_fdd_fd <- uc_fdd_fd %>% 
  rename(
    fundraising_target = fundraisingTarget,
    country_code = CountryCode,
    total_estimated_gift_aid = totalEstimatedGiftAid,
    page_short_name = pageShortName,
    activity_id = activityId,
    activity_type = activityType,
    event_id = eventId,
    event_name = eventName,
    event_date = EventDate,
    expiry_date = expiryDate,
    created_date = CreatedDate,
    )
```
## Adding variable attributes
```{r, include =FALSE}
library(sjlabelled)
uc_fdd_fd %>%
  var_labels(
    charity = "The name of the charity which the fundraiser was set up for.",
    fundraising_target = "The target set, as a goal, for the fundraiser to earn.",
    country_code = "An indicator for the country in which the fundraiser was started. For the data selected for this prediction project, the only country is the United Kingdom.",
    total_estimated_gift_aid = "The total amount of funding from gift aid that the fundraiser received.Gift aid is a tax based scheme enabling registered charities to reclaim tax on a donation made by a UK taxpayer, effectively increasing the amount of the donation. https://en.wikipedia.org/wiki/Gift_Aid",
    page_short_name = "The shortened name of the fundraising page.",
    activity_id = "An identifier number for the fundraising activity.",
    event_id = "An identifier number for the fundraising event.",
    activity_type = "The type of fundraising event, for example a Charity Cycle.",
    event_date = "Date on which the fundraising event occurred or will occur.",
    expiry_date = "The date when fundraising ended, in this case all expiry dates are NA.",
    Owner = "The owner of the fundraiser (the person/organisation which set up the fundraiser).",
    Status = "Whether the fundraiser was Active, Cancelled or Completed at the time in which the API pulled the data.",
    created_date = "Date when the fundraiser was created.",
    wday_created = "The day of the week on which the event was created.",
    hr_created = "The hour of the day in which the fundraiser was created.",
    count_don = "The number of donations.",
    sum_don = "The sum of donations of this fundraiser.",
    med_don = "The median donation of this fundraiser.",
    mn_don = "The mean donation of this fundraiser.",
    dur_cdate = "This is defined as being the interval between the created date and the variable donationDate.",
    dur_edate = "This is defined as being the interval between the EventDate and the donationDate."
    ) %>%
```

## Add meta-data

```{r meta-data}

metadata(uc_fdd_fd)$name <- "Justgiving fundraising pages, aggregated donations"
metadata(uc_fdd_fd)$description <- "Dataset: JustGiving pages pulled via API 2017-19 for 'highly effective' charities; reduced to one row per fundraiser, donation data merged back in; event date more than 25 weeks ago or expiry date passed"
metadata(uc_fdd_fd)$identifier <- "doi:TBA"
metadata(uc_fdd_fd)$datePublished <- "TBA"
metadata(uc_fdd_fd)$creator <- list(
  list(
  "@type" = "Person",
  givenName = "David", familyName = "Reinstein",
  email = "daaronr@gmail.com",
  affiliation = list("@type" = "Organization",
                     name = "University of Exeter")),
  list(
  "@type" = "Person",
  givenName = "Gerhard", familyName = "Riener",
  email = "gerhard.riener@gmail.com",
  affiliation = list("@type" = "Organization",
                     name = "University of Düsseldorf"))
)
  list(
  "@type" = "Person",
  givenName = "Toby", familyName = "Jolly")

metadata(uc_fdd_fd)$citation <- "Jolly, Reinstein, Riener (2019)"
metadata(uc_fdd_fd)$url <-
  "TBA"
metadata(uc_fdd_fd)$temporalCoverage <- "2007-2019 (mainly 2017-19)"
metadata(uc_fdd_fd)$spatialCoverage <- "Mainly UK"
metadata(uc_fdd_fd)$keywords <- c("Charitable giving","Social fundraising")

```

## Codebook

```{r codebook generation, message=FALSE, warning=FALSE}

#uc_fdd_fd_100obs <- uc_fdd[,4] %>% sample_n(50) 

codebook(uc_fdd_fd, survey_repetition = "single", metadata_table = TRUE)

```

