---
title: "Codebook: Donations to JustGiving Fundraiser pages with fundraiser info; plausibly-completed pages"
author: "David Reinstein, Toby Jolly, Gerhard Riener"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

## Setup and import data 

```{r setup-and-import-data, include=FALSE, cache=TRUE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)

ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
library(knitr)
library(haven)
library(tidyverse)
library(codebook)
library(here)

here <- here::here

#rpath <- here::here("Data_exploration","just_giving_power_regression_blocking_scoping")

source(here("R","baseopt_jg.R")) #basic options, definitions, abbreviations for functions

data_folder <- here('input_data')

donations_folder <- file.path(data_folder, 'donations')
fundraising_folder <- file.path(data_folder, 'fundraisers')

#source(here("R","combine_available_data.R")) #check - many parsing failures

source(here("R","scopingfunctions.R")) #tabylstuff, dotplot_func, boxplot_func, geom_mean, sidebyside, huxoptions

```

## Add meta-data

```{r meta-data}

metadata(uc_fdd)$name <- "Donations to Justgiving fundraising pages with page info; UK only, pages with positive amounts raised,  plausibly-completed pages"
metadata(uc_fdd)$description <- "Dataset: All donations to JustGiving pages pulled via API from 2017-19 for 'highly effective' charities; reduced to one row per donation, with info on fundraising pages too. UK-based only, pages with positive amounts raised; event date more than 25 weeks ago or expiry date passed"
metadata(uc_fdd)$identifier <- "doi:TBA"
metadata(uc_fdd)$datePublished <- "TBA"
metadata(uc_fdd)$creator <- list(
  list(
  "@type" = "Person",
  givenName = "David", familyName = "Reinstein",
  email = "daaronr@gmail.com",
  affiliation = list("@type" = "Organization",
                     name = "University of Exeter")),
  list(
  "@type" = "Person",
  givenName = "Gerhard", familyName = "Riener",
  email = "gerhard.riener@gmail.com",
  affiliation = list("@type" = "Organization",
                     name = "University of Düsseldorf"))
)
  list(
  "@type" = "Person",
  givenName = "Toby", familyName = "Jolly")

metadata(uc_fdd)$citation <- "Jolly, Reinstein, Riener (2019)"
metadata(uc_fdd)$url <-
  "TBA"
metadata(uc_fdd)$temporalCoverage <- "2017-19)"
metadata(uc_fdd)$spatialCoverage <- "Mainly UK"
metadata(uc_fdd)$keywords <- c("Charitable giving","Social fundraising")

```

## Codebook

```{r codebook-generation, message=FALSE, warning=FALSE}

codebook(uc_fdd, survey_repetition = "single", metadata_table = TRUE)

```

